# Generated by Django 3.1.2 on 2020-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='released_date',
            field=models.CharField(max_length=10),
        ),
    ]
