# Generated by Django 3.1.2 on 2020-11-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20201113_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
